# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        ./:title

# Server
source:           source/site
destination:      _gh_pages
host:             localhost
port:             9005
baseurl:          /
encoding:         UTF-8

gems:
  - jekyll-sitemap


# Custom vars
current_version:  0.9.0
repo: https://github.com/underlost/dataplay/
site: http://alifewellplayed.com/
